[workspace]
resolver = "3"
members = [
    "crates/cli",
    "crates/cpiolib",
    "crates/minibinrw",
]

[workspace.dependencies]
binrw = "0.15"
cpiolib = { path = "crates/cpiolib" }
easy-ext = "1"
minibinrw = { path = "crates/minibinrw" }
thiserror = "2"
trait-set = "0.3"

[workspace.dependencies.derive_more]
version = "1"
