[package]
name = "rscpio"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
cpiolib.workspace = true
fstr = "0.2.13"
libc = "0.2"
minibinrw.workspace = true
static-slicing = "0.2.0"

[dependencies.rustix]
workspace = true
features = ["fs"]
